[package]
name = "mystic_draw"
version = "2.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = "0.4.6"
libadwaita = "0.1.0"
glib = "0.15.6"
rfd = "0.8.0"
walkdir = "2"
once_cell = "1.9.0"